name: i-n-f-i-x-i-n-g
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
timezone: America/Eastern
future: true
      
plugins: [jekyll-paginate] 
paginate: 3
paginate_path: /page:num/

tag_page_layout: tag_page
tag_page_dir: tag
    
theme: jekyll-theme-tactile
